installer:
  release: "v0.5.3"
  image: "quay.io/devtron/inception"
  tag: "c62d4c30-185-9354"
  
components:
  dashboard:
    image: "quay.io/devtron/dashboard:28591c0e-240-10382"
  devtron:
    image: "quay.io/devtron/test:084c1b09-3263-1895"
    cicdImage: "quay.io/devtron/test:084c1b09-3260-1894"
  argocdDexServer:
    image: "ghcr.io/dexidp/dex:v2.30.2"
    initContainer:
      authenticator: "quay.io/devtron/test:6ea4f92a-382-10432"
      cicdAuthenticator: "quay.io/argoproj/argocd:v2.4.0"
  kubelink:
    image: "quay.io/devtron/kubelink:919924e0-309-10348"
  postgres:
    image: "quay.io/devtron/postgres:11.9.0-debian-10-r26"
  
  migrator:
    image: "quay.io/devtron/migrator:9c933d29-149-10140"
    envVars:
      devtron:
        GIT_BRANCH: "main"
        GIT_HASH: "4fb63eaee87a6f4f4f383ffa4f7c35e31fc4971a"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "e9175e9845c9ca8f6260ea58ce7ad22118244eac"
