installer:
  release: "v0.5.4"
  image: "quay.io/devtron/inception"
  tag: "c62d4c30-185-9354"
  
components:
  dashboard:
    image: "quay.io/devtron/test:2fe90535-3233-1824"
  devtron:
    image: "quay.io/devtron/hyperion:4fb63eae-282-10390"
    cicdImage: "quay.io/devtron/devtron:4fb63eae-313-10391"
  argocdDexServer:
    image: "ghcr.io/dexidp/dex:v2.30.2"
    initContainer:
      authenticator: "quay.io/devtron/authenticator:415f5470-279-6520"
      cicdAuthenticator: "quay.io/argoproj/argocd:v2.4.0"
  kubelink:
    image: "quay.io/devtron/kubelink:919924e0-309-10348"
  postgres:
    image: "quay.io/devtron/postgres:11.9.0-debian-10-r26"
  
  migrator:
    image: "quay.io/devtron/migrator:9c933d29-149-10140"
    envVars:
      devtron:
        GIT_BRANCH: "main"
        GIT_HASH: "4fb63eaee87a6f4f4f383ffa4f7c35e31fc4971a"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "e9175e9845c9ca8f6260ea58ce7ad22118244eac"
